### ISSUE TITLE
Enhanced Nextion Display

### ISSUE THREAD

**Issue by marlock22** [digitalbird01/DigitalBird-Camera-Slider#1]
It was cheaper for me to purchase the enhanced screen. The screen software indicates error: "Model does not match Device Model: NX3224K028_011R", please advise.

**Comment by digitalbird01** [comment]
I have added two .tft files for the Enhanced display with file names ending in 'EN' one for the compact controller the other for the PTZplus controller.

**Comment by digitalbird01** [comment]
These files should work with your display.
All the best
Colin

**Comment by marlock22** [comment]
Thank you, it works great now.

**Comment by digitalbird01** [comment]
Thank you!

**Comment by cinosh07** [comment]
I have the same problem with my nextion display. It's the NX3224K028_011R version.
I've tried with the _en version of the tft file but same result, invalid model. 

I've tried to use the .hmi file but for the ptz version and compiled it on my side and it worked on my display.

Please can your provide the hmi file for the compact version?

**Comment by digitalbird01** [comment]
Compact controller Nextion display files for the Enhanced version of the display have been updated and the .Hmi file provided

**Comment by digitalbird01** [comment]
Can you try the new .tft on your display and let me know that it works ok
Thanks
Colin
